defaults:
  - _self_
  - task@_global_: cartpole_swingup_sparse
  - agent@_global_: mentor
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 4000
update_every_steps: 2
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: False
save_interval: 10000
load_from_id: false
load_id: 0
# wandb
use_wandb: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 0
device: cuda
save_video: true
save_train_video: false
use_tb: true
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 50

hydra:
  run:
    dir: /storage/ssd1/richtsai1103/iso_ted/log/metaworld/multi_5/mentor_open/mentor/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
# python train_dmc.py task@_global_=dog_walk agent@_global_=mentor